config/routes.rb
Rails.application.routes.draw do
 
  

  devise_for :admins

  
  namespace :admin do
    resources :eventos

    resources :campus

    resources :usuarios
    
    root 'eventos#index'
  end
  
  root 'home#index'

 

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates :nome, presence: true
  validates :senha, presence: true
end

app/controllers/admin/usuarios_controller.rb
class Admin::UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin'
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to [:admin,@usuario], notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to [:admin,@usuario], notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to admin_usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :telefone, :login, :senha, :confimaSenha, :campus, :perfil)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :telefone, :login, :senha, :confimaSenha, :campus, :perfil)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/admin/usuarios/_form.html.erb
<%= form_for([:admin,@usuario]) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>
  <div class="field">
    <%= f.label :confimaSenha %><br>
    <%= f.text_field :confimaSenha %>
  </div>
  <div class="field">
    <%= f.label :campus %><br>
    <%= f.text_field :campus %>
  </div>
  <div class="field">
    <%= f.label :perfil %><br>
    <%= f.text_field :perfil %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Exibir', [:admin,@usuario] %>
<%= link_to 'Voltar', admin_usuarios_path %>

app/views/admin/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Usuarios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Login</th>
      <!--<th>Senha</th>
      <th>Confimasenha</th>-->
      <th>Campus</th>
      <th>Perfil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.telefone %></td>
        <td><%= usuario.login %></td>
        <!--<td><%= usuario.senha %></td>
        <td><%= usuario.confimaSenha %></td>-->
        <td><%= usuario.campus %></td>
        <td><%= usuario.perfil %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Exibir', [:admin,usuario] %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Editar', edit_admin_usuario_path(usuario) %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Apagar', [:admin,usuario], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_admin_usuario_path, class: 'btn btn-primary' %>

app/views/admin/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Voltar', admin_usuarios_path %>

app/views/admin/usuarios/show.html.erb
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <p id="notice"><%= notice %></p>
</div>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<p>
  <strong>Confimasenha:</strong>
  <%= @usuario.confimaSenha %>
</p>

<p>
  <strong>Campus:</strong>
  <%= @usuario.campus %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @usuario.perfil %>
</p>

<%= link_to 'Editar', edit_admin_usuario_path(@usuario) %> |
<%= link_to 'Voltar', admin_usuarios_path %>