config/routes.rb
Rails.application.routes.draw do
 
  

  devise_for :admins

  
  namespace :admin do
    resources :eventos

    resources :campus

    resources :usuarios
    
    root 'eventos#index'
  end
  
  root 'home#index'

 

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  
  has_attached_file :foto
  validates_attachment_content_type :foto, :content_type => %w(image/jpeg image/jpg image/png image/gif)
  validates :nome, presence: true
  validates :descricao, presence: true
  validates :local, presence: true
  validates :campu, presence: true
  belongs_to :campu
end

app/controllers/admin/eventos_controller.rb
class Admin::EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin'
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
    
    
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to [:admin,@evento], notice: 'Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to [:admin,@evento], notice: 'Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to admin_eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :descricao, :local, :cronograma, :contatos, :inicio, :fim , :foto, :campu_id)
    end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
    
    
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:nome, :descricao, :local, :cronograma, :contatos, :inicio, :fim , :foto, :campu_id)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<%= simple_form_for @evento, :html => { :multipart => true} do |f| %>



  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> impedindo esse evento de ser gravado.:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    
    <%= f.association :campu , prompt: 'Selecione', label_method: :nome%><br>
    
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao , :class => 'cus-text-area ' %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :cronograma %><br>
    <%= f.text_field :cronograma %>
  </div>
  <div class="field">
    <%= f.label :contatos %><br>
    <%= f.text_field :contatos %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br>
    <%= f.datetime_select :inicio %>
  </div>
  <div class="field">
    <%= f.label :fim %><br>
    <%= f.datetime_select :fim %>
  </div>
  <div class="field">
    <%= f.label :Imagem %><br>
    <p>
      <%= f.file_field :foto %>
    </p>
  </div>
  <div class="actions">
    <%= f.submit  :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Eventos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <!-- <th>Descricao</th> -->
      <th>Campus</th>
      <th>Local</th>
      <th>Cronograma</th>
      <th>Contatos</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nome %></td>
        <!--<td><%= evento.descricao %></td> -->
        <td><%= evento.campu.try(:nome) %></td>
        <td><%= evento.local %></td>
        <td><%= evento.cronograma %></td>
        <td><%= evento.contatos %></td>
        <td><%= l evento.inicio %></td>
        <td><%= l evento.fim %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Exibir', evento %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Editar', edit_evento_path(evento) %></td>
        <td class="btn btn-default btn-sm"><%= link_to 'Apagar', evento, method: :delete, data: { confirm: 'Esta certo disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Evento', new_evento_path, class: 'btn btn-primary'  %>

app/views/eventos/show.html.erb
<script type="text/javascript">
  
  var initialize;
  initialize = function() {
    var coord ="<%= @evento.local %>";
    var x = coord.split(",");
    var mapOptions = {
      center: new google.maps.LatLng(x[0],x[1]),
      zoom: 8,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map-canvas"),
    mapOptions);
  }
  $(document).ready(initialize);
  $(document).on('page:load', initialize);
</script>


<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <p id="notice"><%= notice %></p>
</div>


<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>

<p>
  <strong>Campus:</strong>
  <%= @evento.campu.try(:nome) %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag @evento.foto.url %>
</p>


<p>
  <strong>Descricao:</strong>
  <%= @evento.descricao %>
</p>

<p>
  <strong>Local:</strong>
  <%= @evento.local %>
</p>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<p>
  <strong>Cronograma:</strong>
  <%= @evento.cronograma %>
</p>

<p>
  <strong>Contatos:</strong>
  <%= @evento.contatos %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= l @evento.inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= l @evento.fim %>
</p>

<%= link_to 'Editar', edit_evento_path(@evento) %> |
<%= link_to 'Voltar', eventos_path %>