config/routes.rb
Rails.application.routes.draw do
 
  

  devise_for :admins

  
  namespace :admin do
    resources :eventos

    resources :campus

    resources :usuarios
    
    root 'eventos#index'
  end
  
  root 'home#index'

 

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AconteceNoCampus</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true     
  %>

  <!-- <link href="css/bootstraps.css" rel="stylesheet"> -->
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]
  
  <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCLpvObs66-pCbaxZxJ1Fq9aNtjmnHC8U0&sensor=TRUE">
  </script>-->
  <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script> 
  <script type="text/javascript">
  </script>
</head>
<body> 
  <ul>
  </ul><br /><br /><br />

  <% if admin_signed_in?  %>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      
	      <%= link_to 'Acontece no Campus',  root_path , class:"navbar-brand" %>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
		<li class=""><%= link_to 'Campus', admin_campus_path %></li>
		<li class=""><%= link_to 'Usuarios', admin_usuarios_path %></li>
		<li class="active"><%= link_to 'Eventos', admin_eventos_path %></li>
	      </ul>
	      <ul class="nav navbar-nav pull-right">
		<li class=""><%= link_to 'Sair', destroy_admin_session_path, method: :delete %></li>
	      </ul>
	    </div><!--/.nav-collapse -->
	  </div>
	</nav>
  <% end %>

  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">    
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AconteceNoCampus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- <link href="css/bootstraps.css" rel="stylesheet"> -->
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]
  
  <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCLpvObs66-pCbaxZxJ1Fq9aNtjmnHC8U0&sensor=TRUE">
  </script>-->
  <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script> 
  <script type="text/javascript">
  </script>
</head>
<body> 
  <ul>
  </ul><br /><br /><br />

  <% if admin_signed_in?  %>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      
	      <%= link_to 'Acontece no Campus', root_path, class:"navbar-brand" %>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
		<li class=""><%= link_to 'Campus', campus_path %></li>
		<li class=""><%= link_to 'Usuarios', usuarios_path %></li>
		<li class="active"><%= link_to 'Eventos', eventos_path %></li>
	      </ul>
	      <ul class="nav navbar-nav pull-right">
		<li class=""><%= link_to 'Sair', destroy_admin_session_path, method: :delete %></li>
	      </ul>
	    </div><!--/.nav-collapse -->
	  </div>
	</nav>
  <% end %>

  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">    
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.slim
doctype html
/[if lt IE 7]
  | <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang='#{I18n.locale}'>
/[if IE 7]
  | <html class="no-js lt-ie9 lt-ie8" lang='#{I18n.locale}'>
/[if IE 8]
  | <html class="no-js lt-ie9" lang='#{I18n.locale}'>
/[if IE 9]
  | <html class="no-js ie ie9" lang='#{I18n.locale}'>
| <!--[if (gte IE 9)|!(IE)]<!-->
html.no-js lang='#{I18n.locale}'
  | <!--<![endif]-->
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    - if @title.present?
      title = @title
    - else
      title PapoReto.com — Notícias direto ao ponto, sem enrolação!
    meta name="description" content=""
    meta name='author' content='Startaê — http://www.startae.com.br'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.png', type: 'image/x-icon'
    = stylesheet_link_tag 'application', media: 'all'
  body class="#{{@page_class}}"
    = render 'shared/header'
    = yield
    = render 'shared/footer'
    = render 'shared/development' if Rails.env.development?